package app.frames.Cliente;

import javax.swing.JFrame;

/**
 * @author Breno Lopes de Lima - 31312514
 * @author Vinicius Dutra Cerqueira Rocha - 315112918
 * @author Kepler Nicolai Alves Freitas  - 31222198
 * @version 5.0
 * 
 */

public class Opcoes extends javax.swing.JFrame {

    
    int aux = 0;
    ClientInterface uiprincipal = new ClientInterface();
    
    
    public Opcoes() {
        
        initComponents();
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        BotaoSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnROT47 = new javax.swing.JRadioButton();
        BtnDES = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Seleção de Criptografia");

        buttonGroup1.add(BtnROT47);
        BtnROT47.setText("ROT 47");
        BtnROT47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnROT47ActionPerformed(evt);
            }
        });

        buttonGroup1.add(BtnDES);
        BtnDES.setText(" DES");
        BtnDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BotaoSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BtnROT47)
                .addGap(42, 42, 42)
                .addComponent(BtnDES)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnROT47)
                    .addComponent(BtnDES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
       //if(uiprincipal != null){
           uiprincipal.setTpCrypt(RetornaTPCrypt());
           this.dispose();
      // }
           
            //this.dispose();
        
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BtnROT47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnROT47ActionPerformed
        if(BtnROT47.isSelected()){
            BtnDES.setSelected(false);
        }
    }//GEN-LAST:event_BtnROT47ActionPerformed

    private void BtnDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDESActionPerformed
        if (BtnDES.isSelected()) {
            BtnROT47.setSelected(false);
        }
    }//GEN-LAST:event_BtnDESActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (aux == 0) {
            BtnROT47.setSelected(false);
            BtnDES.setSelected(false);
        } else if (aux == 1) {
            BtnROT47.setSelected(true);
            BtnDES.setSelected(false);
        } else if (aux == 2) {
            BtnROT47.setSelected(false);
            BtnDES.setSelected(true);
        }
    }//GEN-LAST:event_formWindowOpened

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotaoSalvar;
    private javax.swing.JRadioButton BtnDES;
    private javax.swing.JRadioButton BtnROT47;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public int RetornaTPCrypt() {
        int tpcrypt = 0;
        if (BtnROT47.isSelected()) {
            tpcrypt =  1;
        } else if(BtnDES.isSelected()){
            tpcrypt =  2;
        }
        return tpcrypt;
    }
}
